### ISSUE TITLE
Error: Ready check failed: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by Bartaf83** [althjs/redisfire#1]
I have installed redisfire in a server where exist a redis server configured with the authentification (requirepass is set) and when i start redisfire i get this error 

root@REDIS1:~# ./node_modules/.bin/redisfire start
    @@ serviceDir: /root/service
    @@ confDir: /root/conf
    @@ staticDir: /root/static development

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Ready check failed: NOAUTH Authentication required.
    at ReplyParser._parseResult (/root/node_modules/redisfire/node_modules/redis/lib/parsers/javascript.js:41:20)
    at ReplyParser.execute (/root/node_modules/redisfire/node_modules/redis/lib/parsers/javascript.js:138:28)
    at Socket.<anonymous> (/root/node_modules/redisfire/node_modules/redis/index.js:104:27)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

as i have faced this same problem in the past in another server i already know that i have to pass the password in the client.auth() method, so i was looking for where redisfire connects to the redis server (by searching redis.createClient() in the application code) and i found it in 3 different locations (in the utils/redis-helper.js (two times) and in the utils/cli-import.js) and in which i have added

client = redis.createClient(config.redisConf),
    fs = require("fs"),
    jsonMinify = require("node-json-minify");

client.auth('mypassword');

i also was trying to find where socket.io connects to the server i found this line
var socket = io.connect('http://' + location.host + '/redis');
and i don't know where is set the location variable.

and i wonder where i can also configure the redis server ip address (or is it supposed to always be installed in the same server as redis ?

**Comment by Bartaf83** [comment]
well, location.host is this http://stackoverflow.com/a/11379802/1705922 ,i forgot i was in a html page.. i still didn't find the solution for the NOAUTH problem tho.

**Comment by Bartaf83** [comment]
Well, so i s'ppose redisfire is made to be always installed in the same machine where the redis server is, that's why no password nor ip addres are needed to be set.

**Comment by althjs** [comment]
Let me check this issue.
I think it should be supposed to to be configurable for the pre-used modules like redis, socket.io and so on.

**Comment by althjs** [comment]
I published "redisfire@0.0.20" it can configure the redis-client.
Please check the docs "https://github.com/althjs/redisfire#installation"

**Comment by Bartaf83** [comment]
if redis server is run with "requirepass" or use other options for redis, add "redis-client" connfig option to "redisfire-conf.json"

**Comment by Bartaf83** [comment]
I have uninstalled redisfire (npm uninstall redisfire) than installed it again and i edited the redisfire-conf.json like this :
{
    /* redis hash group (Like Firebase Projects) */
    "projects": [
        {
            "name": "theverge",
            "description": "http://www.theverge.com RSS sample data"
        },
        {
            "name": "redisfire-test",
            "description": "redisfire Mocha test project"
        }
    ],
    "requirepass": "mypss"
}

but still i get this : 

root@REDIS1:/# ./node_modules/.bin/redisfire start
@@ serviceDir: /service
@@ confDir: /conf
@@ staticDir: /static development
Error: Error: Ready check failed: NOAUTH Authentication required.
Redis connection failed. Please check redis server is running.

Still i should add the client.auth() or what's the problem ?

**Comment by Bartaf83** [comment]
Can you please tell me what would be the name of the variable i should use to change the redis ip address by the same way in the redisfire-conf.json if that's possible.

**Comment by Bartaf83** [comment]
thanks :) :+1:
